#!/usr/bin/env python3
"""Render the README animation from a recorded transcript.

`docs/assets/amp-demo.gif` is generated by this script from
`docs/assets/demo-transcript.txt`, and the transcript is real output from a real
server (`scripts/README.md` says how to re-record it). Both are in the repository
so the picture on the front page can be reviewed and updated like any other file,
rather than being a binary someone has to regenerate from scratch.

Needs Pillow:  pip install pillow
Run from the repository root:

    python scripts/make_demo_gif.py

Transcript format (see the header of the transcript itself):

    "$ "  a command line, typed out
    "* "  an output line drawn in the accent colour
    "# "  a comment, ignored
    ""    a blank line, a short pause
    else  output, revealed one line at a time
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:  # pragma: no cover - the message is the point
    print(
        "make_demo_gif needs Pillow:  pip install pillow",
        file=sys.stderr,
    )
    raise SystemExit(2) from None

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_TRANSCRIPT = REPO_ROOT / "docs" / "assets" / "demo-transcript.txt"
DEFAULT_GIF = REPO_ROOT / "docs" / "assets" / "amp-demo.gif"
DEFAULT_POSTER = REPO_ROOT / "docs" / "assets" / "amp-demo.png"

# Terminal palette: close to GitHub's dark theme, so the animation does not
# clash with the page it is embedded in.
BACKGROUND = (13, 17, 23)
TITLE_BAR = (22, 27, 34)
BORDER = (48, 54, 61)
DOT_COLOURS = ((255, 95, 86), (255, 189, 46), (39, 201, 63))
TEXT = (201, 209, 217)
PROMPT = (126, 231, 135)
ACCENT = (121, 192, 255)
MUTED = (139, 148, 158)

FONT_CANDIDATES = (
    "C:/Windows/Fonts/consola.ttf",
    "/System/Library/Fonts/Menlo.ttc",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
)

# Frames are cheap to look at and expensive to store, so typing happens in small
# chunks rather than one frame per character.
CHARS_PER_FRAME = 3
TYPING_MS = 45
LINE_MS = 140
PAUSE_MS = 420
FINAL_HOLD_MS = 4200


@dataclass(frozen=True)
class Line:
    """One line of the transcript, already classified."""

    text: str
    kind: str  # command | accent | output | blank


def load_transcript(path: Path) -> list[Line]:
    """Read the transcript, dropping comments and classifying the rest.

    A line that starts with a marker character but not the full marker is an
    error, not output. Writing `*Result` where the format wants `* Result` is easy
    to do and impossible to see: the line renders in the ordinary colour and the
    picture looks fine, only less useful than intended. That is a mistake this
    should refuse to make, so it names the line and stops.
    """
    lines: list[Line] = []
    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if raw.startswith("# "):
            continue
        if raw.startswith("$ "):
            lines.append(Line(raw[2:], "command"))
        elif raw.startswith("* "):
            lines.append(Line(raw[2:], "accent"))
        elif raw.strip() == "":
            lines.append(Line("", "blank"))
        elif raw[:1] in {"*", "$"}:
            raise SystemExit(
                f"{path}:{number}: {raw[:40]!r} looks like a marker but is missing "
                'the space; write "* " or "$ " (or prefix the line with "# " to '
                "comment it out)"
            )
        else:
            lines.append(Line(raw, "output"))
    return lines


def _font(size: int) -> ImageFont.FreeTypeFont:
    for candidate in FONT_CANDIDATES:
        path = Path(candidate)
        if path.exists():
            return ImageFont.truetype(str(path), size)
    raise SystemExit(
        "no monospace font found; add one to FONT_CANDIDATES in this script"
    )


class Terminal:
    """Draws the window, and knows how many lines fit in it."""

    def __init__(self, width: int, font_size: int, line_height: int) -> None:
        self.font = _font(font_size)
        self.ascent, self.descent = self.font.getmetrics()
        self.line_height = line_height
        self.padding = 22
        self.title_height = 34
        self.width = width

    @property
    def usable_width(self) -> int:
        """Horizontal room for text, in pixels."""
        return self.width - 2 * self.padding

    def check_fits(self, lines: list[Line]) -> None:
        """Refuse to draw a line that would run past the right edge.

        Clipped text is invisible in a still review and obvious on the page, so
        this fails instead of producing a picture with a truncated command in it.
        Rerun with a smaller --font-size when it trips.
        """
        offenders = [
            (line.text, int(self.font.getlength(line.text)))
            for line in lines
            if self.font.getlength(line.text) > self.usable_width
        ]
        if offenders:
            worst, width = max(offenders, key=lambda pair: pair[1])
            raise SystemExit(
                f"{len(offenders)} line(s) do not fit in {self.usable_width}px "
                f"(widest {width}px): {worst!r}\n"
                "Rerun with a smaller --font-size, or shorten the transcript."
            )

    def height_for(self, visible_lines: int) -> int:
        return (
            self.title_height
            + self.padding
            + visible_lines * self.line_height
            + self.padding
        )

    def draw(
        self, visible: list[Line], typed_command: str, out_size: tuple[int, int]
    ) -> Image.Image:
        """One frame: the window, plus the lines that have appeared so far."""
        image = Image.new("RGB", out_size, BACKGROUND)
        draw = ImageDraw.Draw(image)

        draw.rectangle((0, 0, out_size[0], self.title_height), fill=TITLE_BAR)
        for index, colour in enumerate(DOT_COLOURS):
            x = 16 + index * 18
            draw.ellipse((x, 11, x + 11, 22), fill=colour)
        draw.text(
            (out_size[0] // 2, self.title_height // 2),
            "amp - agent memory protocol",
            font=self.font,
            fill=MUTED,
            anchor="mm",
        )
        draw.line((0, self.title_height, out_size[0], self.title_height), fill=BORDER)

        y = self.title_height + self.padding
        for line in visible:
            if line.kind == "blank":
                y += self.line_height
                continue
            if line.kind == "command":
                # A green prompt marks the line as something someone typed,
                # which is the whole visual grammar of a terminal.
                draw.text((self.padding, y), "$", font=self.font, fill=PROMPT)
                draw.text(
                    (self.padding + self.font.getlength("$ "), y),
                    typed_command,
                    font=self.font,
                    fill=TEXT,
                )
            else:
                colour = ACCENT if line.kind == "accent" else TEXT
                draw.text((self.padding, y), line.text, font=self.font, fill=colour)
            y += self.line_height

        # A block cursor that trails the last line, so a still frame still reads
        # as a terminal rather than a screenshot.
        if visible:
            last = visible[-1]
            if last.kind == "command":
                cursor_x = self.padding + self.font.getlength(f"$ {typed_command}") + 2
                draw.rectangle(
                    (cursor_x, y - self.line_height + 3, cursor_x + 8, y - 4),
                    fill=PROMPT,
                )
        return image


def build_frames(terminal: Terminal, lines: list[Line]) -> tuple[list, list[int]]:
    """Every frame of the animation, and how long each one is shown."""
    visible: list[Line] = []
    frames: list[Image.Image] = []
    durations: list[int] = []

    # One window size for every frame: the transcript is known up front, so the
    # animation never has to grow or scroll.
    size = (terminal.width, terminal.height_for(len(lines)))

    for line in lines:
        if line.kind == "command":
            visible.append(line)
            for end in range(
                CHARS_PER_FRAME, len(line.text) + CHARS_PER_FRAME, CHARS_PER_FRAME
            ):
                frames.append(terminal.draw(visible[:-1] + [line], line.text[:end], size))
                durations.append(TYPING_MS)
            frames.append(terminal.draw(visible, line.text, size))
            durations.append(PAUSE_MS)
            continue

        visible.append(line)
        frames.append(terminal.draw(visible, "", size))
        durations.append(PAUSE_MS if line.kind == "blank" else LINE_MS)

    durations[-1] = FINAL_HOLD_MS
    return frames, durations


def main() -> int:
    parser = argparse.ArgumentParser(description="Render the README animation.")
    parser.add_argument("--transcript", type=Path, default=DEFAULT_TRANSCRIPT)
    parser.add_argument("--out", type=Path, default=DEFAULT_GIF)
    parser.add_argument("--poster", type=Path, default=DEFAULT_POSTER)
    parser.add_argument("--width", type=int, default=1000)
    parser.add_argument("--font-size", type=int, default=15)
    parser.add_argument("--line-height", type=int, default=21)
    args = parser.parse_args()

    lines = load_transcript(args.transcript)
    terminal = Terminal(args.width, args.font_size, args.line_height)
    # Both directions, before anything is drawn: a frame that clips a command or
    # overflows the window is a broken picture, and a picture is not testable.
    terminal.check_fits([Line("$ " + line.text, line.kind) for line in lines])
    frames, durations = build_frames(terminal, lines)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    # A small palette keeps the file small; the art is flat colour by design.
    palette_frames = [frame.convert("P", palette=Image.Palette.ADAPTIVE, colors=32) for frame in frames]
    palette_frames[0].save(
        args.out,
        save_all=True,
        append_images=palette_frames[1:],
        duration=durations,
        loop=0,
        optimize=True,
        disposal=1,
    )
    # Poster: the finished state, for anywhere an animation will not play.
    frames[-1].save(args.poster)

    size_kb = args.out.stat().st_size / 1024
    print(f"{args.out}: {len(frames)} frames, {frames[0].size[0]}x{frames[0].size[1]}, {size_kb:.0f} KB")
    print(f"{args.poster}: poster frame")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
