"""AMP Server — FastAPI application entry point."""

from __future__ import annotations

import logging
import os
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import Any

from fastapi import APIRouter, FastAPI, Header
from fastapi.responses import JSONResponse, Response

from amp_server.access_control import check_read_access, check_write_access
from amp_server.lifecycle import LifecycleEngine
from amp_server.models import (
    ErrorDetail,
    ErrorResponse,
    LifecycleStatus,
    MemoryAccessPolicy,
    MemoryCell,
    MemoryCellCreate,
    MemoryCellUpdate,
    MemoryIdentity,
    MemoryLifecycle,
    MemoryProvenance,
    MemoryScoring,
    SearchRequest,
    SearchResponse,
    MemoryType,
)
from amp_server.storage.base import InvalidTransitionError, MemoryNotFoundError
from amp_server.storage.chroma import ChromaAdapter

logger = logging.getLogger(__name__)

AMP_VERSION = "0.1.0"

_storage: ChromaAdapter | None = None
_lifecycle: LifecycleEngine | None = None


def get_storage() -> ChromaAdapter:
    assert _storage is not None, "Storage not initialized — lifespan not started"
    return _storage


# ---------------------------------------------------------------------------
# Lifespan
# ---------------------------------------------------------------------------


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _storage, _lifecycle
    persist_dir = os.environ.get("AMP_PERSIST_DIR")
    _storage = ChromaAdapter(persist_directory=persist_dir)
    _lifecycle = LifecycleEngine(_storage)
    logger.info("AMP Server started")
    yield
    logger.info("AMP Server shutting down")


# ---------------------------------------------------------------------------
# App & router
# ---------------------------------------------------------------------------

app = FastAPI(
    title="AMP Server",
    version=AMP_VERSION,
    description="Agent Memory Protocol — Reference Server Implementation",
    lifespan=lifespan,
)

router = APIRouter(prefix="/amp/v1")


# ---------------------------------------------------------------------------
# Error helpers
# ---------------------------------------------------------------------------


def _err(code: str, message: str, details: dict | None = None) -> dict[str, Any]:
    return ErrorResponse(
        error=ErrorDetail(code=code, message=message, details=details or {})
    ).model_dump()


def _missing_agent_id() -> JSONResponse:
    return JSONResponse(
        status_code=401,
        content=_err("MISSING_AGENT_ID", "X-AMP-Agent-ID header is required"),
    )


def _access_denied() -> JSONResponse:
    return JSONResponse(
        status_code=403,
        content=_err("ACCESS_DENIED", "Access denied"),
    )


# ---------------------------------------------------------------------------
# Health & spec
# ---------------------------------------------------------------------------


@router.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok", "amp_version": AMP_VERSION}


@router.get("/spec")
async def spec() -> dict[str, Any]:
    return {
        "amp_version": AMP_VERSION,
        "capabilities": {
            "mcp_compatible": False,
            "storage_backends": ["chroma"],
            "max_cell_size_bytes": 65536,
        },
    }


# ---------------------------------------------------------------------------
# Memory CRUD
# ---------------------------------------------------------------------------


@router.post("/memories", status_code=201)
async def create_memory(
    body: MemoryCellCreate,
    x_amp_agent_id: str | None = Header(default=None),
) -> dict[str, Any]:
    # Determine effective agent_id: header takes priority, fallback to created_by
    agent_id = x_amp_agent_id or body.identity.created_by
    if not agent_id:
        return _missing_agent_id()

    storage = get_storage()
    now = datetime.now(timezone.utc)

    cell = MemoryCell(
        # id is auto-generated by the model with mem_ prefix
        type=body.type,
        content=body.content,
        identity=MemoryIdentity(
            owner_id=body.identity.owner_id,
            owner_type=body.identity.owner_type,
            created_by=agent_id,
            session_id=body.identity.session_id,
        ),
        lifecycle=MemoryLifecycle(
            created_at=now,
            status=LifecycleStatus.ACTIVE,
        ),
        scoring=body.scoring or MemoryScoring(),
        access_policy=body.access_policy or MemoryAccessPolicy(),
        provenance=body.provenance or MemoryProvenance(),
    )
    await storage.save(cell)
    return cell.model_dump(mode="json")


@router.get("/memories/{memory_id}")
async def get_memory(
    memory_id: str,
    x_amp_agent_id: str | None = Header(default=None),
) -> dict[str, Any]:
    if not x_amp_agent_id:
        return _missing_agent_id()

    storage = get_storage()

    try:
        cell = await storage._get_raw(memory_id)
    except MemoryNotFoundError:
        # Per spec §8.4: return 403 regardless of existence to prevent oracle attack
        return _access_denied()

    if cell.lifecycle.status == LifecycleStatus.DELETED:
        return _access_denied()

    if not check_read_access(cell, x_amp_agent_id):
        return _access_denied()

    # Apply access boost (increments access_count, updates last_accessed_at)
    cell = await storage.get(memory_id)
    return cell.model_dump(mode="json")


@router.patch("/memories/{memory_id}")
async def update_memory(
    memory_id: str,
    body: MemoryCellUpdate,
    x_amp_agent_id: str | None = Header(default=None),
) -> dict[str, Any]:
    if not x_amp_agent_id:
        return _missing_agent_id()

    storage = get_storage()

    try:
        cell = await storage._get_raw(memory_id)
    except MemoryNotFoundError:
        return _access_denied()

    if cell.lifecycle.status == LifecycleStatus.DELETED:
        return _access_denied()

    if not check_write_access(cell, x_amp_agent_id):
        return _access_denied()

    updated = await storage.update(memory_id, body)
    return updated.model_dump(mode="json")


@router.delete("/memories/{memory_id}")
async def delete_memory(
    memory_id: str,
    x_amp_agent_id: str | None = Header(default=None),
) -> Response:
    if not x_amp_agent_id:
        return _missing_agent_id()

    storage = get_storage()

    try:
        cell = await storage._get_raw(memory_id)
    except MemoryNotFoundError:
        # Per spec §8.4: return ACCESS_DENIED (not 404) to prevent oracle attack
        return _access_denied()

    if cell.lifecycle.status == LifecycleStatus.DELETED:
        return _access_denied()

    if not check_write_access(cell, x_amp_agent_id):
        return _access_denied()

    try:
        await storage.mark_deleted(memory_id)
    except InvalidTransitionError as exc:
        return JSONResponse(
            status_code=409,
            content=_err("INVALID_TRANSITION", exc.message),
        )

    return Response(status_code=204)


@router.get("/memories")
@router.get("/memories/query")
async def query_memories(
    owner_id: str | None = None,
    type: MemoryType | None = None,
    status: LifecycleStatus | None = None,
    limit: int = 20,
    x_amp_agent_id: str | None = Header(default=None),
) -> dict[str, Any]:
    if not x_amp_agent_id:
        return _missing_agent_id()

    storage = get_storage()
    types_list = [type] if type else None
    status_list = [status] if status else [LifecycleStatus.ACTIVE]

    cells = await storage.query(
        owner_id=owner_id,
        types=types_list,
        status=status_list,
        limit=limit,
    )

    allowed_cells = [c for c in cells if check_read_access(c, x_amp_agent_id)]
    return {
        "results": [c.model_dump(mode="json") for c in allowed_cells],
        "total": len(allowed_cells),
    }


# ---------------------------------------------------------------------------
# Search
# ---------------------------------------------------------------------------


@router.post("/memories/search")
async def search_memories(
    body: SearchRequest,
    x_amp_agent_id: str | None = Header(default=None),
) -> dict[str, Any]:
    if not x_amp_agent_id:
        return _missing_agent_id()

    storage = get_storage()
    results = await storage.search(body, agent_id=x_amp_agent_id)
    response = SearchResponse(results=results, total=len(results), query=body.query)
    return response.model_dump(mode="json")


# ---------------------------------------------------------------------------
# Register router
# ---------------------------------------------------------------------------

app.include_router(router)
